cc_test(
    name = "shm_file_test",
    srcs = ["shm_file_test.cpp"],
    deps = [
        "//trellis/core/ipc/shm:shm_file",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "shm_writer_test",
    srcs = ["shm_writer_test.cpp"],
    deps = [
        "//trellis/core/ipc/shm:shm_writer",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "shm_generation_test",
    srcs = ["shm_generation_test.cpp"],
    deps = [
        "//trellis/core/ipc/shm:shm_file",
        "//trellis/core/ipc/shm:shm_writer",
        "@com_google_googletest//:gtest_main",
        "@fmt",
    ],
)
