filegroup(
    name = "tools",
    srcs = [
        "//trellis/tools/play_cli",
        "//trellis/tools/rec_client_cli",
        "//trellis/tools/sys_client_cli",
        "//trellis/tools/trellis-cli",
    ],
    visibility = ["//visibility:public"],
)
