#!/bin/bash

# This script is meant to be invoked by CI's "build everything" step

set -ex

BAZEL_CACHE_DIR="/github/workspace/.cache/bazel"

if [ -d "$BAZEL_CACHE_DIR" ]; then
  du -sh "$BAZEL_CACHE_DIR"
else
  echo "Bazel cache directory $BAZEL_CACHE_DIR does not exist."
fi

# Running `bazel test ...` will also build all buildable targets (from discussion: https://github.com/bazelbuild/bazel/issues/4257)
bazel test --repository_cache="$BAZEL_CACHE_DIR/repository" --disk_cache="$BAZEL_CACHE_DIR/disk" ...

# Since this script is running inside of a container (as root) the bazel cache
# is owned by root. However, the host system (Github's ubuntu-latest vm)
# is going to attempt to archive the cache to restore it later.
# We can change ownership here to the UID in use outside of the
# container so that there aren't permission failures.
# XXX(bsirang) ideally we can retrieve this UID via an environment variable
echo "Resetting permissions of bazel cache..."
chown -R 1001:1001 "$BAZEL_CACHE_DIR"
