#!/bin/bash

# This script is meant to be invoked by CI's "build everything" step

set -ex

# Running `bazel test ...` will also build all buildable targets (from discussion: https://github.com/bazelbuild/bazel/issues/4257)
bazel test --repository_cache=/github/home/.cache/bazel ...

echo "Resetting permissions of bazel cache..."
chown -R 1001:1001 /github/home/.cache/bazel
