#!/bin/bash

# This script is meant to be invoked by CI's "build everything" step

set -ex

# Running `bazel test ...` will also build all buildable targets (from discussion: https://github.com/bazelbuild/bazel/issues/4257)
bazel test --repository_cache=/github/home/.cache/bazel ...

echo "Resetting permissions of bazel cache..."
chown -R 1000:1000 /github/home/.cache/bazel/_bazel_root
chown -R 1000:1000 /github/home/.cache/bazel


find /github/home/.cache/bazel | xargs ls -l
