load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "file_descriptor",
    hdrs = [
        "file_descriptor.hpp",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "srcs",
    srcs = glob(
        [
            "**/*.hpp",
        ],
    ),
    visibility = ["//trellis:__pkg__"],
)
