cc_binary(
    name = "subscriber",
    srcs = [
        "app.cpp",
        "app.hpp",
        "main.cpp",
    ],
    data = [
        "//trellis/examples:config.yml",
    ],
    deps = [
        "//trellis",
        "//trellis/examples/proto",
    ],
)
