load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "table",
    hdrs = [
        "table.hpp",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "srcs",
    srcs = glob(
        [
            "**/*.hpp",
        ],
        exclude = ["**/test/**"],
    ),
    visibility = ["//trellis:__pkg__"],
)
