cc_binary(
    name = "trellis-cli",
    srcs = [
        "command_handlers.hpp",
        "main.cpp",
        "topic_main.cpp",
    ],
    linkstatic = False,
    deps = [
        "@cxxopts",
        "@trellis//trellis",
    ],
)
