load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "umask_guard",
    hdrs = ["umask_guard.hpp"],
    visibility = ["//visibility:public"],
    deps = [
        "//trellis/core:core_logging",
    ],
)

filegroup(
    name = "srcs",
    srcs = glob(
        [
            "**/*.hpp",
        ],
    ),
    visibility = ["//trellis:__pkg__"],
)
