on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  bazel_build_job:
    runs-on: ubuntu-latest
    name: Bazel build everything
    steps:
      - name: Checkout step
        id: checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: docker buildx
        uses: docker/build-push-action@v2.7.0
        with:
          context: ./docker
          push: false
          load: true
          tags: agtonomy/trellis-runtime:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
      - name: buildifier step
        id: buildifier
        uses: ./.github/actions/buildifier
      - name: shellcheck step
        id: shellcheck
        uses: ./.github/actions/shellcheck
      - name: clang-format step
        id: clangformat
        uses: ./.github/actions/clang-format
      - name: Cache Bazel
        uses: actions/cache@v2
        with:
          path: /home/runner/work/trellis/trellis/.cache/bazel
          key: ${{ runner.os }}-bazel-cache-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-bazel-cache-
      - name: Build step
        id: build
        uses: ./.github/actions/bazel-build
        # This ugly bit is necessary if you don't want your cache to grow forever
        # till it hits GitHub's limit of 5GB.
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
